server:
  port: 8081

spring:
  datasource:
    url: dbc:mysql://localhost:3306/want
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hiberrnate:
        format_sql: true

