server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/want
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hiberrnate:
        format_sql: true
        show_sql: true

